version: '3'

services:
  gabegardener:
    build: .
    container_name: gabegardener
    restart: unless-stopped
    environment:
      - GABEGARDENER_DASHBOARD=true
      - GABEGARDENER_DASHBOARD_PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./config:/root/.gabegardener
