app = "gabegardener"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  GABEGARDENER_DASHBOARD = "true"
  GABEGARDENER_DASHBOARD_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
